-- Update inventor assistant prompts to include data storage capabilities
-- This adds context about how interactions can store and access data

-- HTML Interaction Prompt
UPDATE ai_prompts
SET content = content || E'\n\nDATA STORAGE:\nInteractions can store data using the AI Teacher SDK:\n- Instance Data (anonymous, all students): Use `aiSDK.saveInstanceData(data)` to store data accessible to interaction builders/admins\n- User Progress (per-user): Use `aiSDK.saveUserProgress({ score, completed, customData })` to track user progress\n- Access historical data: `aiSDK.getInstanceDataHistory()` (builders/admins only)\n- Get user progress: `aiSDK.getUserProgress()` to retrieve current user''s progress\n- Mark completed: `aiSDK.markCompleted()` when interaction finishes\n- Increment attempts: `aiSDK.incrementAttempts()` when user retries\n\nData Storage Schemas:\n- Define "Instance Data Schema" in the Data Storage tab to specify what anonymous data to capture\n- Define "User Progress Schema" in the Data Storage tab to specify custom fields beyond required ones (stage/substage IDs, timestamps, attempts, completed are automatic)\n- Required fields for user progress are automatically tracked; custom fields are defined in the schema\n\nExample:\n```javascript\n// Save instance data (anonymous)\nawait aiSDK.saveInstanceData({\n  selectedFragments: [0, 2, 4],\n  timeToFirstSelection: 3.5\n});\n\n// Save user progress\nawait aiSDK.saveUserProgress({\n  score: 85,\n  completed: true,\n  customData: {\n    difficultyRating: 3\n  }\n});\n```'
WHERE assistant_id = 'inventor' AND prompt_key = 'html-interaction';

-- PixiJS Interaction Prompt
UPDATE ai_prompts
SET content = content || E'\n\nDATA STORAGE:\nInteractions can store data using the AI Teacher SDK:\n- Instance Data (anonymous, all students): Use `aiSDK.saveInstanceData(data)` to store data accessible to interaction builders/admins\n- User Progress (per-user): Use `aiSDK.saveUserProgress({ score, completed, customData })` to track user progress\n- Access historical data: `aiSDK.getInstanceDataHistory()` (builders/admins only)\n- Get user progress: `aiSDK.getUserProgress()` to retrieve current user''s progress\n- Mark completed: `aiSDK.markCompleted()` when interaction finishes\n- Increment attempts: `aiSDK.incrementAttempts()` when user retries\n\nData Storage Schemas:\n- Define "Instance Data Schema" in the Data Storage tab to specify what anonymous data to capture\n- Define "User Progress Schema" in the Data Storage tab to specify custom fields beyond required ones (stage/substage IDs, timestamps, attempts, completed are automatic)\n- Required fields for user progress are automatically tracked; custom fields are defined in the schema\n\nExample:\n```javascript\n// Save instance data (anonymous)\nawait aiSDK.saveInstanceData({\n  selectedFragments: [0, 2, 4],\n  timeToFirstSelection: 3.5\n});\n\n// Save user progress\nawait aiSDK.saveUserProgress({\n  score: 85,\n  completed: true,\n  customData: {\n    difficultyRating: 3\n  }\n});\n```'
WHERE assistant_id = 'inventor' AND prompt_key = 'pixijs-interaction';

-- iFrame Interaction Prompt
UPDATE ai_prompts
SET content = content || E'\n\nDATA STORAGE:\nInteractions can store data using the AI Teacher SDK:\n- Instance Data (anonymous, all students): Use `aiSDK.saveInstanceData(data)` to store data accessible to interaction builders/admins\n- User Progress (per-user): Use `aiSDK.saveUserProgress({ score, completed, customData })` to track user progress\n- Access historical data: `aiSDK.getInstanceDataHistory()` (builders/admins only)\n- Get user progress: `aiSDK.getUserProgress()` to retrieve current user''s progress\n- Mark completed: `aiSDK.markCompleted()` when interaction finishes\n- Increment attempts: `aiSDK.incrementAttempts()` when user retries\n\nData Storage Schemas:\n- Define "Instance Data Schema" in the Data Storage tab to specify what anonymous data to capture\n- Define "User Progress Schema" in the Data Storage tab to specify custom fields beyond required ones (stage/substage IDs, timestamps, attempts, completed are automatic)\n- Required fields for user progress are automatically tracked; custom fields are defined in the schema\n\nExample:\n```javascript\n// Save instance data (anonymous)\nawait aiSDK.saveInstanceData({\n  selectedFragments: [0, 2, 4],\n  timeToFirstSelection: 3.5\n});\n\n// Save user progress\nawait aiSDK.saveUserProgress({\n  score: 85,\n  completed: true,\n  customData: {\n    difficultyRating: 3\n  }\n});\n```'
WHERE assistant_id = 'inventor' AND prompt_key = 'iframe-interaction';

-- General Interaction Prompt
UPDATE ai_prompts
SET content = content || E'\n\nDATA STORAGE:\nInteractions can store data using the AI Teacher SDK:\n- Instance Data (anonymous, all students): Use `aiSDK.saveInstanceData(data)` to store data accessible to interaction builders/admins\n- User Progress (per-user): Use `aiSDK.saveUserProgress({ score, completed, customData })` to track user progress\n- Access historical data: `aiSDK.getInstanceDataHistory()` (builders/admins only)\n- Get user progress: `aiSDK.getUserProgress()` to retrieve current user''s progress\n- Mark completed: `aiSDK.markCompleted()` when interaction finishes\n- Increment attempts: `aiSDK.incrementAttempts()` when user retries\n\nData Storage Schemas (Data Storage tab):\n- Define "Instance Data Schema" to specify what anonymous data to capture per interaction instance\n- Define "User Progress Schema" to specify custom fields beyond required ones (stage/substage IDs, timestamps, attempts, completed are automatic)\n- Required fields for user progress are automatically tracked; custom fields are defined in the schema\n- Schemas are JSON objects with field definitions (name, type, required, description)\n\nExample schemas:\nInstance Data Schema:\n```json\n{\n  "fields": [\n    {"name": "selectedFragments", "type": "array", "required": true},\n    {"name": "timeToFirstSelection", "type": "number", "required": false}\n  ]\n}\n```\n\nUser Progress Schema:\n```json\n{\n  "customFields": [\n    {"name": "difficultyRating", "type": "number", "required": false},\n    {"name": "notes", "type": "string", "required": false}\n  ]\n}\n```'
WHERE assistant_id = 'inventor' AND prompt_key = 'general';

