-- Migration: Update personalization options (run on existing DBs)
-- Run: Get-Content docker/postgres/init/06-personalization-options-update.sql | docker exec -i upora-postgres psql -U upora_user -d upora_dev

UPDATE personalization_options SET options = '[
  {"id": "breaking_bad", "label": "Breaking Bad"},
  {"id": "the_sopranos", "label": "The Sopranos"},
  {"id": "game_of_thrones", "label": "Game of Thrones"},
  {"id": "the_office", "label": "The Office"},
  {"id": "friends", "label": "Friends"},
  {"id": "stranger_things", "label": "Stranger Things"},
  {"id": "seinfeld", "label": "Seinfeld"},
  {"id": "succession", "label": "Succession"},
  {"id": "lotr", "label": "Lord of the Rings"},
  {"id": "harry_potter", "label": "Harry Potter"},
  {"id": "marvel", "label": "Marvel Cinematic Universe"},
  {"id": "star_wars", "label": "Star Wars"},
  {"id": "squid_game", "label": "Squid Game"},
  {"id": "dark", "label": "Dark"},
  {"id": "black_mirror", "label": "Black Mirror"},
  {"id": "the_bear", "label": "The Bear"},
  {"id": "ted_lasso", "label": "Ted Lasso"},
  {"id": "the_crown", "label": "The Crown"},
  {"id": "last_of_us", "label": "The Last of Us"},
  {"id": "documentaries", "label": "Documentaries"},
  {"id": "sci_fi", "label": "Sci-Fi"},
  {"id": "fantasy", "label": "Fantasy"},
  {"id": "comedy", "label": "Comedy"},
  {"id": "drama", "label": "Drama"},
  {"id": "thriller", "label": "Thriller"},
  {"id": "action", "label": "Action"}
]'::jsonb WHERE category = 'tv_movies';

UPDATE personalization_options SET options = '[
  {"id": "football", "label": "Football"},
  {"id": "gaming", "label": "Gaming"},
  {"id": "sports", "label": "Sports"},
  {"id": "music", "label": "Music"},
  {"id": "art", "label": "Art"},
  {"id": "coding", "label": "Coding"},
  {"id": "nature", "label": "Nature"},
  {"id": "reading", "label": "Reading"},
  {"id": "movies", "label": "Movies"},
  {"id": "photography", "label": "Photography"},
  {"id": "cooking", "label": "Cooking"},
  {"id": "travel", "label": "Travel"},
  {"id": "fitness", "label": "Fitness"},
  {"id": "hiking", "label": "Hiking"},
  {"id": "cycling", "label": "Cycling"},
  {"id": "running", "label": "Running"},
  {"id": "swimming", "label": "Swimming"},
  {"id": "chess", "label": "Chess"},
  {"id": "board_games", "label": "Board Games"},
  {"id": "drawing", "label": "Drawing"},
  {"id": "gardening", "label": "Gardening"},
  {"id": "meditation", "label": "Meditation"},
  {"id": "podcasts", "label": "Podcasts"},
  {"id": "writing", "label": "Writing"},
  {"id": "dancing", "label": "Dancing"},
  {"id": "playing_instruments", "label": "Playing Instruments"},
  {"id": "design", "label": "Design"},
  {"id": "history", "label": "History"},
  {"id": "science", "label": "Science"},
  {"id": "technology", "label": "Technology"}
]'::jsonb WHERE category = 'hobbies';
